### ISSUE TITLE
Variable $(Rev:.r) not processed correctly for FileVersion and AssembyVersion

### ISSUE THREAD

**Issue by kolu69** [sebastianlux/tfbuildtask-updateAssemblyInfo#1] opened 2016-12-29 22:51 UTC
Hi

Thanks to develop this cool Build-Extension. I have the follow problem with FileVersion and AssembyVersion. (see attachments)

Best regards
kolu69

![logfile_agent_worker](https://cloud.githubusercontent.com/assets/24833341/21556529/8fdd64c4-ce21-11e6-8d6b-ef7da4db1435.png)
![screen_update_assemblyinfo](https://cloud.githubusercontent.com/assets/24833341/21556531/8fddc2ca-ce21-11e6-97e1-0ab9481f288d.png)
![screen_variables](https://cloud.githubusercontent.com/assets/24833341/21556530/8fdd6d48-ce21-11e6-86a8-0df01075d1c9.png)

**Comment by sebastianlux** [comment] 2016-12-31 14:22
Hi kolu69,

I tried to reproduce your issue, but had no success yet using an on premise TFFS2017 for testing with the default build number format _"$(date:yyyyMMdd)$(rev:.r)"_. 
The value is properly processed as **"File version: 20161231.1"** Can you please tell me which "Build number format" you have defined? It can be found in the build definition under the tab "General" .

Thank you!

Sebastian

**Comment by kolu69** [comment] 2017-01-03 12:05
Hi Sebastian

We use the **TFS2015** on Premise with Version **14.102.25423.0 (Update 3)** 
The Field "Build number format" is defined as follows: **$(My.PackageName)_$(My.PackageAssemblyVersion)$(Rev:.r)**

I hope the additional information helps ;)
Thank you for your support

Lucas

**Comment by sebastianlux** [comment] 2017-01-05 17:48
I tried to reproduce the error with the given parameters, but had no success yet. Works as intended.

Iam going to set up a TFS 2015.3 test environment. Can you please provide the version number of the build agents you use?

Thanks

Sebastian

**Comment by kolu69** [comment] 2017-01-06 10:37
sure...

we are using 2 Agents on the same Windows 2008 R2 Server (SP1)

both Agents has the following Version:
![tfs2015 3_agentversions](https://cloud.githubusercontent.com/assets/24833341/21715364/5cf1c7f6-d404-11e6-86a4-ce3764335eb3.png)

Thx

Lucas

**Comment by DrZogg** [comment] 2017-01-09 18:30
Its Very Odd... 

it seems like you need to add your variables to a property group to get them to expand.

I can use $(Build.BuildNumber) if the format is compatible with a assembly version 
When the build number is configured as follows '9.0.0.$(rev:r)' it works.

However, you can't use '9.0.0.$(rev:r) directly inside the File Version in your property tab.

Typically we use '9-0-0-$(rev:r)' as our build number.
If you try to make any modification to build number it also fails to expand.
For example using $(Build.Number.Replace('-','.')) doesn't expand.

This seems to really limit the ability to create versions.

As a following note, I'm using visualstudio.com with what I think is the 2017 build client.
I tried your example of '$(date:yyyyMMdd)$(rev:.r)' and it failed for me.

Thanks,

Christopher

**Comment by sebastianlux** [comment] 2017-01-10 07:52
Thanks for the additional information Christopher!,

I did set up a test project on my VSTS account (visualstudio.com) to reproduce the issue. 
- Created project with a __git__ repository
- Checked in a default .net 4.5 console app
- Created a default "Visual Studio" build definition (left everything with default values) and just added the _AssemblyInfo_ build step.

However, everything worked as expected:
![image](https://cloud.githubusercontent.com/assets/6784951/21797736/20dccd78-d711-11e6-9673-989af4092460.png)

![image](https://cloud.githubusercontent.com/assets/6784951/21797806/72fe8d08-d711-11e6-9c51-744f7c0ba9fe.png)

Can you please provide more details how you fixed the issue for your build definition Christopher? I would like to create some kind of FAQ containing this information.

Thank you!

**Comment by sebastianlux** [comment] 2017-01-29 12:58
Hi again,

I was able to reproduce the issue. The reason is, that _Build Agents_ with a version < 2 (in your case 1.95.3) do not support to __expand variables__.
A more or less detailed description about the issue can be found here:
http://stackoverflow.com/questions/34039705/tfs-2015-can-build-variables-access-other-build-variables

You can fix this by upgrading your _Build Agents_ to version 2.x or by installaing the build task mentioned in the stackoverflow link above (simply add the _Expand Variable_ task as first build step to your build definition).

If you need additional help, just let me know.

Sebastian

**Closed** 2017-02-05 10:49 UTC
Labels: help wanted

**Comment by dbloch3643** [comment] 2017-04-12 15:58
So what could I be missing.  I'm running agent version 2.112.0 and the variable is not expanding.

![image](https://cloud.githubusercontent.com/assets/3717916/24967195/48bc568e-1f77-11e7-91de-7082eae131fe.png)

![image](https://cloud.githubusercontent.com/assets/3717916/24967200/4e387a5c-1f77-11e7-93f1-39c610b241ab.png)

![image](https://cloud.githubusercontent.com/assets/3717916/24967204/51dc46c0-1f77-11e7-9430-99345a4374ea.png)

**Comment by aturlov** [comment] 2017-05-01 21:19
I have installed the latest version and the expressions in Copyright field still don't expand. I am using VSTS 2015, build agent 2.115.0

![image](https://cloud.githubusercontent.com/assets/411697/25595293/3b2972ca-2e92-11e7-85bd-60c2f91bf36e.png)

**Comment by fdahlberg** [comment] 2017-06-30 13:24
I have a similar issue. 
Am trying to set the version to $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r) but the expression is not expanded. Using hosted agent (not sure which version). 
I've also tried to put the same expression in a Variable but that's not expanded either. 

This is the log:

![image](https://user-images.githubusercontent.com/9571179/27737377-39f4899a-5da8-11e7-8f70-e1130e969e36.png)


 
Any help on this would be appreciated!

Thanks
Fredrik Dahlberg

**Comment by DrZogg** [comment] 2017-06-30 13:37
Dahlberg,


Set the "build number format" in the options page and use $(rev:r) instead of $(Rev.r).
You can also set a description on the page in the same format.
When you're editing the build there will be an option tab toward the top of the page.

I use something like bellow for the build number format
10-0-0-$(rev:r)

From here you can use $(Build.BuildNumber) and it expands correctly in the variables page or elsewhere.
We expand the build number further in the variables page into multiple variations.

I hope this helps..

Microsoft should fix this.

-Chris

**Comment by fdahlberg** [comment] 2017-06-30 13:46
Thanks Chris! 
That's what I ended up doing. 

I set Build Number Format under Options to:
$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)
and version in the Update AssemblyInfo task to:
$(Build.BuildNumber)
and that works fine

It seems strange that none of the variables will be expanded though. Is there a build task you need to add for this to happen?

Fred

**Comment by DrZogg** [comment] 2017-06-30 13:53
Fred,

No this is just Ugly TFS behavior but remember other variables will expand.
Its just the version variable that seems to be special.

Additionally, there are a lot of transform step out there that you can use to parse your build number to get parts from what you created.
One thing to keep in mind is that the actual value you set is what TFS records as the build.

Then from there you can transform it to other things.
For example we take our build of 10-0-0-123 and convert it to 10.0.0.123 as a transform before the code compiles.
We also run a custom build step to update the AssemblyInfo.cs files so the binaries have the correct version.

Sorry, yes this is just much harder than it should be.

-Chris

**Comment by renatotkr** [comment] 2017-07-07 17:38
same issue here, can't use $(rev:.r) directly in the task

looks like it's not supported

Microsoft/vsts-tasks#3585

**Comment by pabrams** [comment] 2017-09-20 19:16
Same issue here.  I have Agent version 2.112, so I don't think that's the problem.

**Comment by pabrams** [comment] 2017-09-20 19:22
It works fine when I use $(Build.BuildNumber)  instead of $(date:yyyyMMdd)$(rev:.r), and I also moved the update AssemblyInfo task after the build task (can't understand why he suggests putting it BEFORE the build task, anyway), because I assume the buildnumber isn't available until after the build...
